pull_request_rules:
  - name: automatic merge for Dependabot devDependencies pull requests
    conditions:
      - author~=^(dependabot\[bot\]|scala-steward)$
      - title~=^build\(deps-dev\)
    actions:
      merge:
        method: squash
