pull_request_rules:
  - name: automatic merge for Dependabot devDependencies pull requests
    conditions:
      - author~=^(dependabot\[bot\]|scala-steward)$
      - check-success=build_and_test (22.x, ubuntu-latest)
      - check-success=build_and_test (22.x, windows-latest)
      - check-success=build_and_test (24.x, ubuntu-latest)
      - check-success=build_and_test (24.x, windows-latest)
      - title~=^build\(deps-dev\)
    actions:
      merge:
        method: squash
