pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build_and_test (10.x)
      - check-success=build_and_test (12.x)
    actions:
      merge:
        method: merge
