packages:
  - packages/*

catalog:
  '@eslint/js': ^10.0.0
  '@stryker-mutator/core': 9.6.1
  '@stryker-mutator/mocha-runner': 9.6.1
  '@stryker-mutator/typescript-checker': 9.6.1
  '@stryker-mutator/vitest-runner': 9.6.1
  eslint: ^10.0.0

# 2 days, in minutes
minimumReleaseAge: 2880

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver
  - chokidar
  - '@octokit/endpoint'

minimumReleaseAgeExclude:
  # Renovate security update: vite@8.0.5
  - vite@8.0.5

allowBuilds:
  nx: true
  unrs-resolver: false
