version = "3.11.2"
project.git = true
lineEndings = unix
maxColumn = 120
align.preset = more
runner.dialect = scala213source3

assumeStandardLibraryStripMargin = true

rewrite.rules = [SortImports, SortModifiers, RedundantParens, RedundantBraces, PreferCurlyFors]
rewrite.redundantBraces.stringInterpolation = true
rewrite.scala3.convertToNewSyntax = true
