name: 'Setup CI'
description: 'Set up npm, Java, and cache for CI'
inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '20.x'
    required: false
  setup-java:
    description: 'Whether to set up Java'
    default: 'false'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: master
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - uses: actions/setup-java@v4
      if: ${{ inputs.setup-java == 'true' }}
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'sbt'
    - uses: actions/cache@v4
      with:
        path: .nx
        key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nx-
    - run: npm ci
      shell: bash
