name: 'Setup CI'
description: 'Set up npm, Java, and cache for CI'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '24.x'
    required: false
  setup-java:
    description: 'Whether to set up Java'
    default: 'false'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: master
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/setup-java@v5
      if: ${{ inputs.setup-java == 'true' }}
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1
    - uses: actions/cache@v4
      if: ${{ github.actor == 'stryker-mutator' }}
      with:
        path: .nx/cache
        key: ${{ runner.os }}-nx-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nx-${{ inputs.node-version }}-
          ${{ runner.os }}-nx-
    - run: npm ci
      shell: bash
